### ISSUE TITLE
bug: issue with using mixins

### ISSUE THREAD

**Issue by codekeyz** [google/reflectable.dart#324] opened 2023-12-21 21:17 UTC
```shell
[INFO] Generating build script completed, took 171ms
[INFO] Reading cached asset graph completed, took 66ms
[INFO] Checking for updates since last build completed, took 509ms
[SEVERE] reflectable on test/config/config_test.dart:
Missing MixinApplication member: Symbol("isAugmentation")
[SEVERE] reflectable on test/config/config_test.dart:

type 'Null' is not a subtype of type 'bool'
[INFO] Running build completed, took 4.8s
[INFO] Caching finalized dependency graph completed, took 37ms
[SEVERE] Failed after 4.8s
```

```dart
mixin Foo {

}

class Bar with Foo { }
```

This doesn't work and I have searched the codebase for references to `Symbol("isAugmentation")` but can't find any. Any help

**Comment by eernstg** [comment] 2024-01-05 11:29
This is being corrected in https://github.com/google/reflectable.dart/pull/326, which is an update that allows reflectable to use the most recent version of the analyzer.

Some changes to the analyzer turn out to be breaking changes for reflectable, because reflectable needs to use a few APIs of the analyzer that aren't "officially" available, and this is one of those cases.

For now, you should be able to use a more strict analyzer version constraint in order to have an analyzer where this member `isAugmentation` hasn't yet been introduced, that is, a version from before than https://github.com/dart-lang/sdk/commit/2c54a11c23a8e66e6859a4248241d550f36464ca.

**Comment by eernstg** [comment] 2024-01-05 11:35
Actually, `isAugmentation` was added way back in analyzer 4.4.0, but I haven't seen this failure before (using versions of analyzer which are more recent than 4.4.0), so your usage of reflectable must have visited a new code path.

You could try to pin your pubspec.yaml to some older versions of the analyzer and see if it helps.

**Comment by eernstg** [comment] 2024-01-05 11:43
Just wondering, did you override the version constraint on the analyzer? I can't reproduce the issue locally with the existing set of tests and using reflectable 4.0.5.

**Comment by codekeyz** [comment] 2024-01-11 16:47
Weird you're unable to reproduce it. 

I tried upgrading some of reflectable's dependencies but that didn't work. I think you're right  with the Analyzer being the cause. I'll try pinning the version and see it that works.

Also, super thankful for your work on this library. It's really the key enabler for my Backend Framework purely in Dart.

**Comment by eernstg** [comment] 2024-03-16 14:00
Closing: #326 has now landed.

**Closed by eernstg** 2024-03-16 14:00 UTC
