### ISSUE TITLE
This reflector does not match anything

### ISSUE THREAD

**Issue by hiranthaR** [google/reflectable.dart#307] opened 2023-01-09 01:04 UTC
some times I get these error while generating. This reflector does not match anything

```dart
rules.dart
abstract class Rule {
  bool isApplicable();
  bool process();
}

and_rule.dart
import 'package:my_app/utils/rule_engine/rule.dart';
import 'package:my_app/utils/rule_engine/rule_reflector.dart';

@rulesReflector
class AndRule implements Rule {
  final List<Rule> _rules = [];

  @override
  bool isApplicable() => _rules.every((rule) => rule.isApplicable());

  @override
  bool process() => _rules
      .where((rule) => rule.isApplicable())
      .every((rule) => rule.process());

  AndRule withRule({required Rule rule}) {
    _rules.add(rule);
    return this;
  }
}

not_rule.dart
import 'package:grub_pos/utils/rule_engine/rule.dart';
import 'package:grub_pos/utils/rule_engine/rule_reflector.dart';

@rulesReflector
class NotRule implements Rule {
  final Rule _rule;

  NotRule({required Rule rule}) : this._rule = rule;

  @override
  bool isApplicable() => _rule.isApplicable();

  @override
  bool process({List<dynamic>? inputs}) => !_rule.process();
}


rule_reflector.dart
import 'package:collection/collection.dart';
import 'package:reflectable/reflectable.dart';

class RuleReflector extends Reflectable {
  const RuleReflector() : super(invokingCapability);

  ClassMirror? getInstanceMirror(String qualifiedName) {
    return annotatedClasses
        .firstWhereOrNull((cls) => cls.simpleName == qualifiedName);
  }
}

const RuleReflector ruleReflector = const RuleReflector();
```
```
flutter pub run build_runner build --delete-conflicting-outputs
```

**Comment by eernstg** [comment] 2023-01-09 19:47
The warning 'This reflector does not match anything' indicates that the given program contains a reflector (that is, a subclass of `Reflectable`) which isn't associated with any declarations at all. Let's call it `reflector`. Then it means that `reflector.reflect(myObject)` will fail no matter which object `myObject` is, and `reflector.reflectType(MyType)` will fail no matter which type `MyType` is. This could very well be a bug, hence the warning. But in the case where you have reflectors that are never used then this warning can be ignored.

**Comment by hiranthaR** [comment] 2023-01-15 15:48
@eernstg Actually I was able to fix this warning by, creating `Objects from the Classes that I need to generate`. Generator will not generate anything if you dont use the class anywhere

**Comment by eernstg** [comment] 2023-01-16 10:57
That's surprising, so let me ask the analyzer team:

@scheglov, does the analyzer perform some kind of tree shaking? The situation might be that a class `C` is removed entirely from the program before the reflectable code generator gets to see it, because the program doesn't seem to use that class at all. This would explain that no data is generated for this class by the reflectable code generator, but if an instance of `C` is created by the program then the data supporting reflection about `C` _is_ generated.

**Comment by scheglov** [comment] 2023-01-17 00:35
No, the analyzer does not do any tree shaking. I don't know how you use it, but in any case, if you ask for parsed AST - you get everything, if you ask for element model - you get everything regardless whether a specific `ClassElement` is used anywhere, similarly for resolved AST. So, any shortcutting would be above the analyzer.

**Comment by eernstg** [comment] 2023-01-17 10:01
@hiranthaR, based on the information from @scheglov I would not expect the 'does not match anything' warning to be emitted in the situation you describe. So this sounds like a bug. However, package 'grub_pos' does not seem to be on pub.dev. Do you have a small and self-contained example where this behavior occurs?

**Comment by cheogm28** [comment] 2023-05-10 12:40
Hello I have the same warnning in my case I have this 
`class RestAPI extends Reflectable {
  const RestAPI()
      : super(
            typeAnnotationQuantifyCapability,
            invokingCapability,
            declarationsCapability,
            typeRelationsCapability,
            metadataCapability);
}
`

then another file with 
`const RestApi = RestAPI();`

and in another file I use the RestApi by importing it.
`@RestApi
class Adaptor....`
 
I never create an object of type Adaptor

**Comment by eernstg** [comment] 2023-05-10 13:01
Hi @cheogm28, it should be no problem to have `const RestApi = RestAPI();` in a different library than the one that declares `RestAPI`.

(By the way, it is highly confusing that `RestApi` is capitalized, the standard capitalization would be `restApi` for the variable and `RestApi` for the class. But I think I can read that, now ;-)

But if you get that warning then it might be because you are running the reflectable code generator on a library 'something.dart' such that the library that declares `class Adaptor` isn't reachable via import paths from `something.dart`. If that's true, and you also do not reach any other declaration which is included for processing by `RestApi` then you will indeed not obtain support for reflection on anything at all, and then you get this warning.

In general, you need to run the reflectable code generator on a library which is the entry point ("the main library") for the entire program whose declarations you wish to get some amount of reflection support for. If any given declaration is not reachable from that entry point via zero or more import links then it will not be seen by the reflectable code generator, and there will not be any support for reflection on that declaration.

**Comment by eernstg** [comment] 2024-03-11 13:32
> Simply adding `import 'test_class.dart';` to the main file will result in `TestClass` being added to the generated file. If you now also add an import for `second_test_class.dart`, this class will also be included in the generated file.

That's a very fundamental property of the reflectable code generator (and of Dart in general): Your program is identified by an entry point (that is, a library that exports a `main` function), and it includes every library which is imported directly from the entry point plus everything which is imported indirectly (from libraries that are imported by libraries that are imported from the entry point, etc).

In the example project, `test_class.dart` and `second_test_class.dart` are not part of the program defined by `reflectable_issue_308.dart`, so they might as well not exist.

Hence, this is just working as intended: If you want to have reflection support for a particular library then it certainly must be part of your program. In this case it's enough that some library in your program imports `second_test_class.dart`, because that library in turn imports `test_class.dart`.

> Now that a year has passed, have you gotten any more insight into the issue

The fact that the reflectable code generator works on a given program is an absolutely fundamental property, so there's no need to include any new insights for that (I mentioned this property [here](https://github.com/google/reflectable.dart/issues/307#issuecomment-1542171470) as well).

The original posting [reported that](https://github.com/google/reflectable.dart/issues/307#issuecomment-1383184550) code for reflection support with certain classes would occur if the program created instances of said class, and otherwise not (so there was nothing about adding or removing imports, it was all about adding or removing a `new` expression).

I'll close this issue because no further information has been given on a situation where such a thing would occur.

**Closed by eernstg** 2024-03-11 13:32 UTC
