### ISSUE TITLE
InconsistentAnalysisException when building project

### ISSUE THREAD

**Issue by maxime-aubry** [google/reflectable.dart#213] opened 2020-07-02 11:19 UTC
Hello.

I try to build my project [https://github.com/maxime-aubry/EasyValidation/tree/feature/20190924_AddNewValidators](https://github.com/maxime-aubry/EasyValidation/tree/feature/20190924_AddNewValidators)
I got an InconsistentAnalysisException error.
I upgraded the lasts versions of Flutter and Dart as told is another issue of Reflectable repo, but this exception still appears.
Could you help me please ?

This is the command line I used :
```
flutter packages pub run build_runner build
```

**Comment by eernstg** [comment] 2020-07-02 11:37
This would be the issue that is reported as https://github.com/dart-lang/build/issues/2634, and it has not yet been resolved. The issue does not arise when `build.yaml` builds a single target, so a workaround would be to do that.

**Comment by maxime-aubry** [comment] 2020-07-02 11:45
Thanks a lot :)

**Comment by AndrewMorsillo** [comment] 2020-08-12 21:31
Also running into this, quite confusing as someone new to dart! It looks based on the closure of  dart-lang/build#2634 that some fix is indeed needed in this repo?

**Comment by eernstg** [comment] 2020-08-13 10:12
> closure of dart-lang/build#2634

Right, the workaround was new to me. The time is scarce, but I'll try to use that workaround when possible.

**Comment by maxime-aubry** [comment] 2020-09-07 14:13
Hello.
are there improvements about this bug ?
thanks.

**Comment by eernstg** [comment] 2020-09-07 16:29
Not yet. I've allocated some time to look into it on Friday, that should at least reveal whether the workaround works in this case.

**Comment by eernstg** [comment] 2020-09-11 14:46
https://github.com/google/reflectable.dart/pull/220 up for review. Seems to work! ;-)

**Comment by eernstg** [comment] 2020-09-11 15:39
@maxime-aubry, are you getting an `InconsistentAnalysisException` in a situation where you are generating code with reflectable for more than one entry point (that is: more than one library containing a `main` function which is the root of the set of libraries that will run as a single program)? If so then this is likely a duplicate of #198.

**Comment by eernstg** [comment] 2020-09-29 16:13
Resolved by #220.

**Closed by eernstg** 2020-09-29 16:13 UTC
